export const ActionType = {
  SET_PRODUCTS_ELECTRONICS: "SET_PRODUCTS_ELECTRONICS",
  SET_PRODUCTS_JEWELERY: "SET_PRODUCTS_JEWELERY",
  SET_PRODUCTS_MENS_CLOTHING: "SET_PRODUCTS_MENS_CLOTHING",
  SET_PRODUCTS_WOMENS_CLOTHING: "SET_PRODUCTS_WOMENS_CLOTHING",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  INCREASE_QTY: "INCREASE_QTY",
  DECREASE_QTY: "DECREASE_QTY",
  REMOVE: "REMOVE",
};
