export const ActionType = {
  SET_PRODUCTS_ELECTRONICS: "SET_PRODUCTS_ELECTRONICS",
  SET_PRODUCTS_JEWELERY: "SET_PRODUCTS_JEWELERY",
  SET_PRODUCTS_MENS_CLOTHING: "SET_PRODUCTS_MENS_CLOTHING",
  SET_PRODUCTS_WOMENS_CLOTHING: "SET_PRODUCTS_WOMENS_CLOTHING",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
